// Edit this list to swap in real phrases. Pool size should stay >= 24 to support 5x5 cards.
window.PHRASES = [
  // Catchphrases
  "tohle nás nikam neposune",
  "jaká je konverze?",
  "kolik?",
  "za mě ok",
  "no chance",
  "co to řeší?",
  "pojďme dál",
  "paráda",
  "já bych tam dal...",
  "kdo to vlastní?",
  "dej tam ticket",
  "to jsme už řešili",
  "kde jsou data?",
  "musíme to měřit",
  "co říkají uživatelé?",
  "jaký je success metric?",
  "to je out of scope",
  "ASAP",
  "potřebuju focus",
  "co bude další krok?",
  // Behaviors
  "položí otázku mezi dveřmi a odejde",
  "přijde 5 minut pozdě",
  "během prezentace si otevře jiný tab",
  "změní téma uprostřed věty",
  "odpoví jen na první větu zprávy",
  "zareaguje pouze na screenshot, ne na text",
  "ukáže graf z hlavy bez podkladů",
  "zmíní zákazníka, kterého včera potkal",
  "vyžaduje data, co nemáme",
  "rozhodne věc během 30 sekund",
  "odmítne návrh jednou větou",
  "tichý feedback: jen 🙂",
  "zařadí item do parking lotu",
  "prokritizuje font na slidu",
  "řekne 'to je nice-to-have'",
  "začne větu 'já bych...'",
  // Marie's additions
  "přijmutej hover",
  "jde si pro vodu",
  "jde si vyzvednout wolt",
  "to nám víc aut neprodá",
  // Magdalena's additions
  "pojďme dál prosím",
  "odpovídáš na dotaz, nedá ti dopovědět a už se ptá někoho jiného na něco",
  "to jsem určitě neschválil/neřekl",
  "no, tak co s tím uděláme?",
  "pohádal jsem se o tom s Kubou",
  "to jsem nikdy neviděl",
  "tohle jsem určitě neschválil",
  "popírá co minule řekl/schválil"
];
