-- Seed phrases verbatim from phrases.js. Idempotent: re-runs are no-ops thanks to the unique constraint.

insert into phrases (text) values
  ('tohle nás nikam neposune'),
  ('jaká je konverze?'),
  ('kolik?'),
  ('za mě ok'),
  ('no chance'),
  ('co to řeší?'),
  ('pojďme dál'),
  ('paráda'),
  ('já bych tam dal...'),
  ('kdo to vlastní?'),
  ('dej tam ticket'),
  ('to jsme už řešili'),
  ('kde jsou data?'),
  ('musíme to měřit'),
  ('co říkají uživatelé?'),
  ('jaký je success metric?'),
  ('to je out of scope'),
  ('ASAP'),
  ('potřebuju focus'),
  ('co bude další krok?'),
  ('položí otázku mezi dveřmi a odejde'),
  ('přijde 5 minut pozdě'),
  ('během prezentace si otevře jiný tab'),
  ('změní téma uprostřed věty'),
  ('odpoví jen na první větu zprávy'),
  ('zareaguje pouze na screenshot, ne na text'),
  ('ukáže graf z hlavy bez podkladů'),
  ('zmíní zákazníka, kterého včera potkal'),
  ('vyžaduje data, co nemáme'),
  ('rozhodne věc během 30 sekund'),
  ('odmítne návrh jednou větou'),
  ('tichý feedback: jen 🙂'),
  ('zařadí item do parking lotu'),
  ('prokritizuje font na slidu'),
  ('řekne ''to je nice-to-have'''),
  ('začne větu ''já bych...'''),
  ('přijmutej hover'),
  ('jde si pro vodu'),
  ('jde si vyzvednout wolt'),
  ('to nám víc aut neprodá'),
  ('odpovídáš na dotaz, nedá ti dopovědět a už se ptá někoho jiného na něco'),
  ('to jsem určitě neschválil/neřekl'),
  ('no, tak co s tím uděláme?'),
  ('pohádal jsem se o tom s Kubou'),
  ('to jsem nikdy neviděl'),
  ('popírá co minule řekl/schválil')
on conflict (text) do nothing;
